jobs:
  include:
#     - os: windows
#       language: c
#       arch: amd64
#       script:
#         - clang -coverage -O0 hello_world.c -o hello_world
#         - ./hello_world
    - os: linux
      language: java
      dist: bionic
      arch: amd64
      script:
        - javac hello_world.java
        - java HelloWorld
    - os: linux
      language: java
      dist: focal
      arch: amd64
      script:
        - javac hello_world.java
        - java HelloWorld

